export enum NotificationType {
	LIKE_PRODUCT = 'LIKE_PRODUCT',
	LIKE_ARTICLE = 'LIKE_ARTICLE',
	COMMENT_PRODUCT = 'COMMENT_PRODUCT',
	COMMENT_ARTICLE = 'COMMENT_ARTICLE',
	FOLLOW_MEMBER = 'FOLLOW_MEMBER',
	MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
	PRODUCT_APPROVED = 'PRODUCT_APPROVED',
	PRODUCT_REJECTED = 'PRODUCT_REJECTED',
	SYSTEM = 'SYSTEM',
}

export enum NotificationStatus {
	WAIT = 'WAIT',
	READ = 'READ',
}

export enum NotificationGroup {
	PRODUCT = 'PRODUCT',
	ARTICLE = 'ARTICLE',
	MEMBER = 'MEMBER',
	SYSTEM = 'SYSTEM',
}
